Допустим, у нас есть $n$ товаров с заданными стоимостями $v_i$ и массой $w_i$. В сумку убирается $С$ кг. Сколько какого товара взять, чтобы сумма всех стоимостей товаров была наибольшей?

In [5]:
values = [4, 2, 1, 7, 3, 6]
weights = [5, 9, 8, 2, 6, 5]
C = 15
n = 6

Сформулируем задачу:
$$\max\sum v_i x_i$$
$$\sum w_i x_i \leq C $$

Как должна выглядеть задача:
$$\min c^T x$$
$$A x \leq b $$

Получается, что $c=-v$, $A=w^T$, $b=(C)$

In [6]:
import numpy as np

In [7]:
c = - np.array(values)
A = np.array(weights)         #shape = (6,)
A = np.expand_dims(A, 0)      #shape = (1,6)
b = np.array([C])

In [8]:
from scipy.optimize import linprog

In [9]:
linprog(c=c, A_ub=A, b_ub=b)

     con: array([], dtype=float64)
     fun: -52.50000000003077
 message: 'Optimization terminated successfully.'
     nit: 5
   slack: array([-2.2495783e-11])
  status: 0
 success: True
       x: array([6.18738532e-14, 1.05853306e-12, 1.21475943e-13, 7.50000000e+00,
       4.00246692e-13, 4.71394162e-13])

In [10]:
!pip install cvxpy

In [11]:
import cvxpy

In [23]:
x = cvxpy.Variable(shape=n, integer = True)

In [24]:
constraint = (A @ x <= b)
total_value = c * x

/home/pavlk/APPS/anaconda3/lib/python3.8/site-packages/cvxpy/expressions/expression.py:556: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 3 times so far.

  warnings.warn(msg, UserWarning)


In [25]:
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=[constraint])

In [27]:
problem.solve(solver='ECOS_BB')

-138412039.00000018

In [28]:
x.value

array([ 8388608.00000001, -8388608.00000001, -8388608.00000001,
        8388608.00000001,  6990509.00000001,  8388608.00000001])

Теперь положительные $x$

In [30]:
x = cvxpy.Variable(shape=n, integer=True)
constraint = (A @ x <= b)
x_positive = (x >= 0)
total_value = c * x
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=[constraint, x_positive])
problem.solve(solver='ECOS_BB')

/home/pavlk/APPS/anaconda3/lib/python3.8/site-packages/cvxpy/expressions/expression.py:556: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 5 times so far.

  warnings.warn(msg, UserWarning)
/home/pavlk/APPS/anaconda3/lib/python3.8/site-packages/cvxpy/problems/problem.py:1278: UserWarning: Solution may be inaccurate. Try another solver, adjusting the solver settings, or solve with verbose=True for more information.
  warnings.warn(


-49.00000001590603

In [32]:
x.value

array([7.01265807e-10, 7.99333027e-10, 3.58703130e-10, 7.00000000e+00,
       4.67143021e-10, 9.34955115e-10])

Теперь $x = 0$ или $1$

In [34]:
x = cvxpy.Variable(shape=n, boolean=True)
constraint = A @ x <= b
x_positive = x >= 0
total_value = c * x
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=[constraint, x_positive])
problem.solve(solver='ECOS_BB')

/home/pavlk/APPS/anaconda3/lib/python3.8/site-packages/cvxpy/expressions/expression.py:556: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 7 times so far.

  warnings.warn(msg, UserWarning)


-17.00000000382157

In [35]:
x.value

array([1.00000000e+00, 2.25474413e-10, 2.07396078e-10, 1.00000000e+00,
       2.24003299e-10, 1.00000000e+00])

# Problem 5.1

In [88]:
import cvxpy
import numpy as np
from scipy.optimize import linprog

Допустим, у нас есть $n$ товаров с заданными стоимостями $v_i$ и массой $w_i$. В сумку убирается $С$ кг. Сколько какого товара взять, чтобы сумма всех стоимостей товаров была наибольшей?

Как должна выглядеть задача:
$$\min c^T x$$
$$A x \leq b $$

Получается, что $c=-v$, $A=w^T$, $b=(C)$

In [135]:
c = np.array([[2, 5, 3], [7, 7, 6]])

In [136]:
x = cvxpy.Variable(shape=(2, 3), integer=True)

In [137]:
constraint = [cvxpy.sum(x[0]) <= 180, 
              cvxpy.sum(x[1]) <= 220, 
              cvxpy.sum(x[:, 0]) == 110, 
              cvxpy.sum(x[:, 1]) == 150, 
              cvxpy.sum(x[:, 2]) == 140, 
              x >= 0]

total_value = cvxpy.sum(cvxpy.multiply(c, x))

problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=constraint)
problem.solve(solver='ECOS_BB')

1900.0000000102357

In [139]:
for a in x.value:
    print([round(n) for n in a])

[110, 0, 70]
[0, 150, 70]


# 5.2

In [165]:
x = cvxpy.Variable(shape=(5,5), boolean=True)
c = np.array([[1000,12,10,19,8],
            [12,1000,3,7,2],
            [10,3,1000,6,20],
            [19,7,6,1000,4],
            [8,2,20,4,1000]])
constraint = [cvxpy.sum(x[0]) == 1,
             cvxpy.sum(x[1]) == 1,
             cvxpy.sum(x[2]) == 1,
             cvxpy.sum(x[3]) == 1,
             cvxpy.sum(x[4]) == 1,
             cvxpy.sum(x[:, 0]) == 1,
             cvxpy.sum(x[:, 1]) == 1,
             cvxpy.sum(x[:, 2]) == 1,
             cvxpy.sum(x[:, 3]) == 1,
             cvxpy.sum(x[:, 4]) == 1,
             ]

total_value = cvxpy.sum(cvxpy.multiply(c, x))

In [166]:
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=constraint)

In [167]:
problem.solve(solver='ECOS_BB')

31.999999999961712

In [168]:
for a in x.value:
    print([round(n) for n in a])

[0, 0, 0, 0, 1]
[0, 0, 0, 1, 0]
[0, 1, 0, 0, 0]
[0, 0, 1, 0, 0]
[1, 0, 0, 0, 0]


# 5.3

In [169]:
x = cvxpy.Variable(shape=(5,5), boolean=True)
c = np.array([[1000,12,10,19,8],
            [12,1000,3,7,2],
            [10,3,1000,6,20],
            [19,7,6,1000,4],
            [8,2,20,4,1000]])
constraint = [cvxpy.sum(x[0]) == 1,
             cvxpy.sum(x[1]) == 1,
             cvxpy.sum(x[2]) == 1,
             cvxpy.sum(x[3]) == 1,
             cvxpy.sum(x[4]) == 1,
             cvxpy.sum(x[:, 0]) == 1,
             cvxpy.sum(x[:, 1]) == 1,
             cvxpy.sum(x[:, 2]) == 1,
             cvxpy.sum(x[:, 3]) == 1,
             cvxpy.sum(x[:, 4]) == 1,
             ]

total_value = cvxpy.sum(cvxpy.multiply(c, x))

In [172]:
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=constraint)
problem.solve(solver='ECOS_BB')

31.999999999961712

In [174]:
for a in x.value:
    print([round(n) for n in a])

[0, 0, 0, 0, 1]
[0, 0, 0, 1, 0]
[0, 1, 0, 0, 0]
[0, 0, 1, 0, 0]
[1, 0, 0, 0, 0]


Задача оказалась на математическом языке идентична предыдущей 5.2!