In [1]:
import numpy as np

In [2]:
apartment = np.array([59.50, 31.40, 19, 22, 60550, 2])

In [3]:
share_living_space = apartment[1]/apartment[0]

In [4]:
apartment = np.delete(apartment, [0, 1])

In [5]:
apartment = np.append(apartment, share_living_space)

In [6]:
share_living_space

0.5277310924369748

In [7]:
apartment.shape

(5,)

In [8]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

In [9]:
a = np.array([120, 150, 90])
z = np.array([130, 130, 130])
t = np.array([2, 3, 2.5])
e = 72

In [10]:
tr = t * e
family = a + z + tr

In [11]:
tr, family

(array([144., 216., 180.]), array([394., 496., 400.]))

In [12]:
d = np.array([3,4,5,9])
s = np.array([1,5,3,6])
t = -d*200 + s*400
t

array([-200, 1200,  200,  600])

In [13]:
v = np.array([4,6,1])
np.dot(v, v)**0.5

7.280109889280518

In [14]:
import pandas as pd
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})


In [15]:
v = Hut_Paradise_DF.values
v

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]])

In [16]:
v[4]

array([40, 33,  1,  6, 20, 16])

In [17]:
v[:,3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5])

In [18]:
v[2,3]

10

In [19]:
len(v) #  or v.shape[0]

9

In [20]:
v[:, 1] - v[:, 5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

In [21]:
v[:, 0] / 2.5

array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

In [22]:
time = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])
time.shape

(9,)

In [23]:
v[:, 4]@time  # or
np.dot(v[:, 4], time)

1348

In [24]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [25]:
u@v, u@w, v@w

(0, 0, 0)

In [26]:
2*v - 3*w

array([-3, 14,  3,  4,  2])

In [27]:
(2*v - 3*w) @ u

0

In [28]:
u_len = np.linalg.norm(u)
v_len = np.linalg.norm(v)
w_len = np.linalg.norm(w)

In [29]:
u/u_len, v/v_len, w/w_len

(array([0.8660254 , 0.        , 0.28867513, 0.28867513, 0.28867513]),
 array([ 0.        ,  0.33333333,  0.        ,  0.66666667, -0.66666667]),
 array([ 0.21320072, -0.85280287, -0.21320072,  0.        , -0.42640143]))

In [30]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])


In [31]:
Inc = pd.DataFrame([Husband_Income, Wife_Income, Mother_In_Law_Income]).values.T
Inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [32]:
Cons = pd.DataFrame([Husband_Сonsumption, Wife_Сonsumption, Mother_In_Law_Сonsumption]).values.T
Cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [33]:
Inc_Tax = Inc * (1-0.13)
Inc_Tax[0]

array([ 87. , 130.5,  78.3])

In [34]:
Inc_Tax - Cons

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

In [35]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [36]:
A@x

array([26, 30])

In [37]:
A=np.array( [ [1,9,8,5] , [3,6,3,2] , [3,3,3,3], [0,2,5,9], [4,4,1,2] ] )
B=np.array( [ [1,-1,0,1,1] , [-2,0,2,-1,1] ] )

In [38]:
A.shape, B.shape

((5, 4), (2, 5))

In [39]:
np.dot(B,A)

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [40]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [41]:
G = np.matrix([x, y, z])
G

matrix([[ 1,  2,  1,  0,  4],
        [ 2,  1, -1,  1,  0],
        [-1,  1, -1,  0,  0]])

In [42]:
np.dot(G, G.T)

matrix([[22,  3,  0],
        [ 3,  7,  0],
        [ 0,  0,  3]])

In [43]:
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])


In [44]:
Count_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

In [45]:
Price_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

In [46]:
cc = Count_DF.values
pp = Price_DF.values
cc * pp

array([[20. ,  7.5, 12. , 12. , 10. ],
       [ 3.6, 52.5,  3. , 25. ,  6. ],
       [24. , 24. ,  0. , 15. ,  8. ],
       [ 7.2,  9.6, 50.4, 11.2, 10. ],
       [15. , 87.5, 54. , 25. , 27. ],
       [50. , 15. ,  6. , 34. , 30. ],
       [24.2,  1. ,  6. , 12.5, 34. ],
       [31.5,  0. , 77.5, 31. , 56. ]])

In [47]:
cc * pp @ np.array([0.2, 0.2, 0.3, 0.1, 0.1])

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [48]:
cc * pp @ (1 - np.array([0.2, 0.2, 0.3, 0.1, 0.1]))

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [49]:
A = np.array( [[ 8 , 6 ,11],[ 7 , 5 , 9],[ 6 ,10,  6]])

In [50]:
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [51]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [52]:
Binary packages for some distributions are provided by @jgeboski. If packages for your distribution are not provided by @jgeboski, you will need to locate a third-party repository, or build the plugin.vv = np.matrix([v1, v2, v3, v4]).T
vv

matrix([[ 9,  2,  4,  3],
        [10,  0,  0, -4],
        [ 7,  5,  0,  3],
        [ 7,  1,  4, -1],
        [ 9,  4,  1, -4]])

In [53]:
np.linalg.matrix_rank(vv)

4

In [54]:
vvG = np.dot(vv.T, vv)
vvG

matrix([[360,  96,  73, -35],
        [ 96,  46,  16,   4],
        [ 73,  16,  33,   4],
        [-35,   4,   4,  51]])

In [55]:
np.linalg.det(vvG)

3716647.9999999995

In [56]:
np.linalg.inv(vvG)

matrix([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
        [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
        [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
        [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])