In [1]:
import numpy as np

In [27]:
v1 = np.array([1, 2, 1])
v2 = np.array([-5, 1, 1])
A = np.matrix([v1, v2]).T
b = np.matrix([1, 2, 2])
A, b

(matrix([[ 1, -5],
         [ 2,  1],
         [ 1,  1]]),
 matrix([[1, 2, 2]]))

In [14]:
np.linalg.matrix_rank(A) < np.linalg.matrix_rank(np.matrix([v1, v2, b]))

3

In [18]:
A.T * A

matrix([[ 6, -2],
        [-2, 27]])

In [30]:
A.T * b.T

matrix([[ 7],
        [-1]])

In [60]:
wk = np.linalg.inv(A.T * A) * (A.T * b.T)

Всё что выше - не то.

In [63]:
wk = np.matrix([1, 1]).T

In [64]:
bk = A * wk
bk

matrix([[-4],
        [ 3],
        [ 2]])

In [65]:
e = b.T - bk
e

matrix([[ 5],
        [-1],
        [ 0]])

Задание 2.6.3

In [71]:
v1 = np.array([1, -3, 1, 1])
v2 = np.array([2, 1, 2, -1])
A = np.matrix([v1, v2]).T
b = np.matrix([1, 4, 5, 0]).T
A, b

(matrix([[ 1,  2],
         [-3,  1],
         [ 1,  2],
         [ 1, -1]]),
 matrix([[1],
         [4],
         [5],
         [0]]))

In [74]:
A.T * A

matrix([[12,  0],
        [ 0, 10]])

In [77]:
A.T * b

matrix([[-6],
        [16]])

In [79]:
np.linalg.inv(A.T*A) * (A.T*b)

matrix([[-0.5],
        [ 1.6]])

In [81]:
-29.3-.26*0.2+8.4*6

21.048000000000005

In [90]:
v0 = np.array([11, 8])
1/np.linalg.norm(v0 - v0.mean()) * (v0 - v0.mean())


array([ 0.70710678, -0.70710678])

In [91]:
# Загрузка библиотек
import numpy as np # для работы с массивами
import pandas as pd # для работы DataFrame 
import seaborn as sns # библиотека для визуализации статистических данных
import matplotlib.pyplot as plt # для построения графиков

%matplotlib inline

In [92]:
data = pd.read_csv('Admission_Predict_Ver1.1.csv')

In [108]:
data.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [109]:
data.columns  # собака, в Chance of Admit в конце строки стоит пробел ::angry::

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [96]:
data.shape

(500, 9)

In [98]:
data.corr(method='pearson')

Serial No.  GRE Score  TOEFL Score  University Rating  \
Serial No.           1.000000  -0.103839    -0.141696          -0.067641   
GRE Score           -0.103839   1.000000     0.827200           0.635376   
TOEFL Score         -0.141696   0.827200     1.000000           0.649799   
University Rating   -0.067641   0.635376     0.649799           1.000000   
SOP                 -0.137352   0.613498     0.644410           0.728024   
LOR                 -0.003694   0.524679     0.541563           0.608651   
CGPA                -0.074289   0.825878     0.810574           0.705254   
Research            -0.005332   0.563398     0.467012           0.427047   
Chance of Admit      0.008505   0.810351     0.792228           0.690132   

                        SOP      LOR       CGPA  Research  Chance of Admit   
Serial No.        -0.137352 -0.003694 -0.074289 -0.005332          0.008505  
GRE Score          0.613498  0.524679  0.825878  0.563398          0.810351  
TOEFL Score        0.644410  0.541563  0.810574  0.467012          0.792228  
University Rating  0.728024  0.608651  0.705254  0.427047          0.690132  
SOP                1.000000  0.663707  0.712154  0.408116          0.684137  
LOR                0.663707  1.000000  0.637469  0.372526          0.645365  
CGPA               0.712154  0.637469  1.000000  0.501311          0.882413  
Research           0.408116  0.372526  0.501311  1.000000          0.545871  
Chance of Admit    0.684137  0.645365  0.882413  0.545871          1.000000

In [136]:
data.loc[data.Research == 1].corr()

Serial No.  GRE Score  TOEFL Score  University Rating  \
Serial No.           1.000000  -0.094895    -0.140706          -0.058624   
GRE Score           -0.094895   1.000000     0.824170           0.614739   
TOEFL Score         -0.140706   0.824170     1.000000           0.602445   
University Rating   -0.058624   0.614739     0.602445           1.000000   
SOP                 -0.109004   0.613318     0.629436           0.723126   
LOR                  0.010475   0.443374     0.436199           0.573881   
CGPA                -0.049214   0.806720     0.784173           0.692237   
Research                  NaN        NaN          NaN                NaN   
Chance of Admit      0.024458   0.802439     0.787180           0.713094   

                        SOP      LOR       CGPA  Research  Chance of Admit   
Serial No.        -0.109004  0.010475 -0.049214       NaN          0.024458  
GRE Score          0.613318  0.443374  0.806720       NaN          0.802439  
TOEFL Score        0.629436  0.436199  0.784173       NaN          0.787180  
University Rating  0.723126  0.573881  0.692237       NaN          0.713094  
SOP                1.000000  0.591858  0.717750       NaN          0.708238  
LOR                0.591858  1.000000  0.564794       NaN          0.588558  
CGPA               0.717750  0.564794  1.000000       NaN          0.892489  
Research                NaN       NaN       NaN       NaN               NaN  
Chance of Admit    0.708238  0.588558  0.892489       NaN          1.000000

In [137]:
data.loc[data.Research == 0].corr()

Serial No.  GRE Score  TOEFL Score  University Rating  \
Serial No.           1.000000  -0.165248    -0.185665          -0.093655   
GRE Score           -0.165248   1.000000     0.680668           0.384715   
TOEFL Score         -0.185665   0.680668     1.000000           0.495748   
University Rating   -0.093655   0.384715     0.495748           1.000000   
SOP                 -0.199090   0.371424     0.476563           0.607496   
LOR                 -0.018579   0.365864     0.470956           0.484262   
CGPA                -0.138537   0.678476     0.696774           0.516427   
Research                  NaN        NaN          NaN                NaN   
Chance of Admit     -0.002771   0.603827     0.622458           0.428580   

                        SOP      LOR       CGPA  Research  Chance of Admit   
Serial No.        -0.199090 -0.018579 -0.138537       NaN         -0.002771  
GRE Score          0.371424  0.365864  0.678476       NaN          0.603827  
TOEFL Score        0.476563  0.470956  0.696774       NaN          0.622458  
University Rating  0.607496  0.484262  0.516427       NaN          0.428580  
SOP                1.000000  0.618680  0.547098       NaN          0.470188  
LOR                0.618680  1.000000  0.562517       NaN          0.542528  
CGPA               0.547098  0.562517  1.000000       NaN          0.752714  
Research                NaN       NaN       NaN       NaN               NaN  
Chance of Admit    0.470188  0.542528  0.752714       NaN          1.000000

In [153]:
TnC = data.loc[data['Research'] == 0, ['TOEFL Score', 'CGPA']].values
y = data.loc[data['Research'] == 0, ['Chance of Admit ']].values
A = np.column_stack((np.ones(220), TnC))

In [154]:
w_hat = np.linalg.inv(A.T@A) @ A.T@y

In [155]:
w_hat

array([[-1.04486443],
       [ 0.00442727],
       [ 0.14807744]])

In [234]:
w_hat[0] + w_hat[1]*107 + w_hat[2]*9.1

array([0.77635853])

In [158]:
-1.045 + 107*0.004 + 9.1*0.148

0.7297999999999998

Теперь со стандартизацией признаков

In [223]:
T = data.loc[data['Research'] == 0, 'TOEFL Score'].values

In [224]:
t00 = T.mean()
t11 = T - t00
t22 = np.linalg.norm(t11)
T_std = t11 / t22

In [225]:
C = data.loc[data['Research'] == 0, 'CGPA'].values

In [226]:
c00 = C.mean()
c11 = C - c00
c22 = np.linalg.norm(c11)
C_std = c11 / c22

In [227]:
A_std = np.column_stack((T_std, C_std))

In [228]:
y00 = y.mean()
y11 = y - y00
y22 = np.linalg.norm(y11)
y_std = y11 / y22

In [229]:
w_hat_std = np.linalg.inv(A_std.T@A_std) @ A_std.T@y_std
w_hat_std

array([[0.19044768],
       [0.62001517]])

In [230]:
T_new = (107 - t00) / t22
T_new

0.04223527047096074

In [231]:
C_new = (9.1 - c00) / c22
C_new

0.1247725145688624

In [232]:
new_std = w_hat_std[0] * T_new + w_hat_std[1] * C_new
new_std

array([0.08540446])

In [233]:
new_std * y22 + y00

array([0.77635853])

2.16

In [253]:
x1 = np.array([[1, 2, 1, 1]])
x2 = np.array([[70, 130, 65, 60]])
x1st = (x1 - x1.mean())/np.linalg.norm(x1 - x1.mean())
x2st = (x2 - x2.mean())/np.linalg.norm(x2 - x2.mean())
x1st, x2st

(array([[-0.28867513,  0.8660254 , -0.28867513, -0.28867513]]),
 array([[-0.19829369,  0.85927267, -0.28642422, -0.37455475]]))

In [265]:
A = np.matrix([[1, 0.9922], [0.9922, 1]])
B = np.linalg.eig(A)
B

(array([1.9922, 0.0078]),
 matrix([[ 0.70710678, -0.70710678],
         [ 0.70710678,  0.70710678]]))

In [266]:
res = (0.70710678*x1st + 0.70710678*x2st)

In [268]:
(res - res.mean())/np.linalg.norm(res - res.mean())

array([[-0.24396044,  0.86433557, -0.28811186, -0.33226327]])