In [2]:
import numpy as np
import pandas as pd

In [3]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована

array([4.6808178e-310, 0.0000000e+000, 7.9050503e-323, 7.9050503e-323,
       2.3715151e-322])

In [31]:
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [33]:
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [38]:
np.eye(4) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [8]:
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7

array([ 0,  7, 14])

In [9]:
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
a = np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)
a

array([[6, 6, 1],
       [2, 0, 9],
       [4, 2, 0]])

In [11]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
my_secret
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [12]:
 np.ones((2,2,2)) 

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [13]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [14]:
sum([x[-1] for x in big_secret])

3154.332495807108

In [15]:
res = int()
for i, j in enumerate(big_secret):
    res += j[i]
print(res)

121.37188663699624


In [16]:
res2 = 1
for i, j in enumerate(big_secret):
    res2 *= j[-5+i]
print(res2)

341505315559.2347


In [17]:
big_secret[1::2, 1::2] = 1
big_secret[::2, ::2] = -1

In [18]:
big_secret

array([[-1.00000000e+00,  1.00000000e+01, -1.00000000e+00,
         5.60000000e+01, -1.00000000e+00,  2.40000000e+01,
        -1.00000000e+00,  7.00000000e+01, -1.00000000e+00,
         1.40000000e+02, -1.00000000e+00,  6.00000000e+01,
        -1.00000000e+00,  1.30000000e+02, -1.00000000e+00,
         2.24000000e+02, -1.00000000e+00,  9.60000000e+01,
        -1.00000000e+00,  1.90000000e+02, -1.00000000e+00,
         3.08000000e+02, -1.00000000e+00,  1.32000000e+02,
        -1.00000000e+00,  2.50000000e+02, -1.00000000e+00,
         3.92000000e+02, -1.00000000e+00,  1.68000000e+02,
        -1.00000000e+00,  3.10000000e+02, -1.00000000e+00,
         4.76000000e+02, -1.00000000e+00,  2.04000000e+02,
        -1.00000000e+00,  3.70000000e+02, -1.00000000e+00,
         5.60000000e+02, -1.00000000e+00,  2.40000000e+02,
        -1.00000000e+00,  4.30000000e+02, -1.00000000e+00,
         6.44000000e+02, -1.00000000e+00,  2.76000000e+02,
        -1.00000000e+00,  4.90000000e+02, -1.00000000e+0

In [19]:
res3 = int()
for i, j in enumerate(big_secret):
    res3 += j[i]
print(res3)

-1.0


In [20]:
res4 = 1
for i, j in enumerate(big_secret):
    res4 *= j[-5+i]
print(res4)

-1.0


In [40]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

In [43]:
great_secret.shape

(100, 3)

In [49]:
np.cos(great_secret[0]).sum()

0.16006721889793019

In [52]:
great_secret[great_secret>50].sum()

5470.0

In [54]:
great_secret.flatten()[150]

7.0710678118654755

In [60]:
great_secret.sort(axis=0)
great_secret[-1].sum()

115.12148016521353

In [79]:
a_weight = np.array([34,43,40,44,41,54,39,48,35,60])
a_height = np.array([135,160,163,147,138,149,136,154,137,165])
a_mark = np.array([4,5,4.3,5,4.7,3.9,4.2,4.9,3.7,4.6])

In [76]:
np.median(a_weight)

42.0

In [80]:
np.mean(a_weight)

43.8

In [85]:
corr = np.corrcoef(a_weight, a_mark) # a_weight, a_height, a_mark
corr

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

In [86]:
np.std(a_mark)

0.4517742799230607

In [88]:
np.std(a_weight) ** 2

60.36

In [93]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])

In [96]:
my_sin = np.sin(my_array)
my_sin.sum()

-0.05812430261413351

In [103]:
my_sin[1:4,1:4] = 1
my_sin.sum()

7.571718421269144

In [108]:
my_sin[:,:4].reshape(10,2)[:,0].sum()

2.4057172058139544

In [115]:
# bigdata = np.array([x ** 2 for x in range(100, 1001) if x%2 == 1])
bigdata = np.array([x ** 2 for x in range(101, 1000, 2)])
np.median(bigdata)

302501.0

In [118]:
np.std(bigdata)

292095.0301991155

In [119]:
np.corrcoef(bigdata[1::2], bigdata[::2])

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])